openapi: 3.0.0
info:
  title: MapChap API
  version: "3.0.0"

x-yc-apigateway:
  cors:
    origin: '*'
    methods: '*'
    allowedHeaders: '*'

paths:
  /api/health:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK

  /api/db-test:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK

  /api/categories:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK

  /api/app-info:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK

  /api/auth/telegram:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK
    options:
      x-yc-apigateway-integration:
        type: dummy
        content:
          '*': ''
        http_code: 200
        http_headers:
          Access-Control-Allow-Origin: '*'
          Access-Control-Allow-Methods: '*'
          Access-Control-Allow-Headers: '*'

  /api/users/{telegram_id}:
    parameters:
      - name: telegram_id
        in: path
        required: true
        schema:
          type: string
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK

  /api/offers:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK
    options:
      x-yc-apigateway-integration:
        type: dummy
        content:
          '*': ''
        http_code: 200
        http_headers:
          Access-Control-Allow-Origin: '*'
          Access-Control-Allow-Methods: '*'
          Access-Control-Allow-Headers: '*'

  /api/articles:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK

  /api/boosts/plans:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekri024dh40qmoh0m5
      responses:
        '200':
          description: OK
